### PR TITLE
fix: Use Node 20

### LINKED ISSUE #528: Node 16 actions are deprecated
I noticed when I ran one of our builds that Github is saying that Node 16 actions are deprecated, and this action was listed.

I'm unsure how easy it is to just move to Node 20?

### PR DESCRIPTION
**Pull request by akatov**
fixes #528

### CODE REVIEW

**Comment by brianjmurrell** [comment]
What needs to happen to get this PR landed?

**Comment by belitre** [comment]
Hi @akatov, first sorry for the delay with the PR. Looks like our Prow is not happy right now 😞 , so let me check what is happening and I'll try to merge this as soon as possible!

**Pull request merged**
