### PR TITLE
doc: Update prow link in README

### PR DESCRIPTION
**Pull request by jcfr**
Redirecting to the readme section of the page helps understand more
quickly what is "prow".

| Before | After |
|--|--|
| image | image |

### CODE REVIEW

**Comment by jcfr** [comment]
@givanov @alexouzounis @belitre  When you have a chance, I would appreciate if you could have a look at PR and the other three I submitted.

They are related to documentation improvements and they should all include a before & after screenshot as well as a detailed commit message motivating each change.

Thanks again for your help :pray: 

In the meantime, let me know if there is anything else I could do :rocket:

**Comment by belitre** [comment]
Hi @jcfr 

First, thank you very much for the pull requests! And sorry I didn't notice these before!

Cheers!

**Comment by jcfr** [comment]
> First, thank you very much for the pull requests! And sorry I didn't notice these before!

@belitre Of course, and thanks for reviewing and moving forward with the integration :pray:

**Pull request merged**
