### PR TITLE
feat: Add a SHA param

### PR DESCRIPTION
**Pull request by chancancode**
This allows specifying which commit the status check is for. It preserves the current default (the HEAD SHA in pull requests) but falls back to `github.sha` which is more generally available (on `push` events, for example).

This also allows overriding the default completely for other use cases (e.g. a scheduled task updating commit statuses).

### CODE REVIEW

**Comment by belitre** [comment]
Hi @chancancode 

First sorry for the delay, and thanks for your PR!

I had to fix a wee problem with PRs from forks so... could you rebase your PR please?

Also, I'm going to change the name of the PR, just adding `feat:` at the beginning, that way as soon as we merge it the actions we have configured will create a release automatically.

Thank you very much.

**Comment by chancancode** [comment]
@belitre Sure I have rebased. I think I also gave maintainers to push to the branch, so feel free to make other edits as you see fit.

However, I have since tested this on our repos and it didn't work – there is a check somewhere that hard errors with "action only works on pull_request events" when building on master (which is my primary motivation for making this change). I haven't dug in to see where that is coming from and why that restriction is put in place, but I think that has to be addressed also for this feature to be useful (for my use case anyway).

**Comment by chancancode** [comment]
From what I can tell, this action seems to be doing a lot more things than I was expecting, when all I really want is a simple wrapper to the commit status API. So, if, for some reason, given all your other goals, that it wasn't appropriate to use this action for my use case, I can totally accept that and am happy to fork etc.

**Comment by belitre** [comment]
Hi @chancancode 

Yes, this action is focused in pull requests, that error you can see is here: https://github.com/ouzi-dev/commit-status-updater/blob/master/src/utils.ts#L5

It shouldn't be very difficult to make it work for push events too, so if you want to add the push event is ok for me.

If you want to just fork it or create a new one it should be easy too, please feel free to ask any questions if you need help :)

Cheers!

**Pull request closed without merging**
